branchProtectionRules:
  - pattern: main
    isAdminEnforced: true
    requiredApprovingReviewCount: 1
    requiresCodeOwnerReviews: true
    requiresStrictStatusChecks: true
    requiredStatusCheckContexts:
      - "ci/kokoro: Samples test"
      - "ci/kokoro: System test"
      - "ci/kokoro: System test with Multiplexed Session"
      - lint
      - test (18)
      - test (20)
      - test (22)
      - cla/google
      - windows
      - OwlBot Post Processor
      - Build with Airlock
permissionRules:
  - team: yoshi-admins
    permission: admin
  - team: jsteam-admins
    permission: admin
  - team: jsteam
    permission: push
