introduction: |-
        [Cloud Spanner](https://cloud.google.com/spanner/docs/) is a fully managed, mission-critical, relational database service that
        offers transactional consistency at global scale, schemas, SQL (ANSI 2011 with extensions),
        and automatic, synchronous replication for high availability.

body: |-
        ## Multiplexed Sessions

        Spanner's Multiplexed Sessions is now default enabled session mode in node client. This feature helps reduce
        session management overhead and minimize session-related errors.

        For a detailed explanation on multiplexed sessions, please refer to the [official documentation](https://cloud.google.com/spanner/docs/sessions#multiplexed_sessions).

        ## Regular Sessions

        To use regular sessions, disable the multiplexed sessions and set the following environment variables to `false`:

        * **For Read-Only Transactions:**
        - `GOOGLE_CLOUD_SPANNER_MULTIPLEXED_SESSIONS`
        * **For Partitioned Operations:**
        - `GOOGLE_CLOUD_SPANNER_MULTIPLEXED_SESSIONS`
        - `GOOGLE_CLOUD_SPANNER_MULTIPLEXED_SESSIONS_PARTITIONED_OPS`
        * **For Read-Write Transactions:**
        - `GOOGLE_CLOUD_SPANNER_MULTIPLEXED_SESSIONS`
        - `GOOGLE_CLOUD_SPANNER_MULTIPLEXED_SESSIONS_FOR_RW`

        For a detailed explanation on session modes and env configurations, please refer to the [official documentation](https://cloud.google.com/spanner/docs/sessions).
